version: '3.8'

services:
  lica_api_dev:
    container_name: lica_api_dev
    image: lica_api_dev:1.0.0
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      - lica_mongodb 
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    restart: unless-stopped

  lica_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db 
    restart: unless-stopped

networks:
  default:
    driver: bridge